# Generated by Django 3.2 on 2021-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
