# Generated by Django 3.2 on 2021-05-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('fimage', models.ImageField(upload_to='uploads/sell/')),
                ('mimage', models.ImageField(upload_to='uploads/sell')),
                ('bimage', models.ImageField(upload_to='uploads/sell')),
                ('author', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
