# Generated by Django 3.2 on 2021-05-02 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0008_sellproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
