# Generated by Django 3.2 on 2021-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0010_sellproduct_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='bimage',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='fimage',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='mimage',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
    ]
