# Generated by Django 3.2 on 2021-05-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0011_auto_20210502_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellproduct',
            old_name='bimage',
            new_name='b_image',
        ),
        migrations.RenameField(
            model_name='sellproduct',
            old_name='fimage',
            new_name='f_image',
        ),
        migrations.RenameField(
            model_name='sellproduct',
            old_name='mimage',
            new_name='m_image',
        ),
    ]
