# Generated by Django 3.2 on 2021-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0012_auto_20210502_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='b_image',
            field=models.ImageField(upload_to='uploads/sell/'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='f_image',
            field=models.ImageField(upload_to='uploads/sell/'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='m_image',
            field=models.ImageField(upload_to='uploads/sell/'),
        ),
    ]
