# Generated by Django 3.2 on 2021-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0016_auto_20210503_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='b_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='f_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='m_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
