# Generated by Django 3.2 on 2021-05-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0017_auto_20210503_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_image', models.ImageField(upload_to='media/')),
                ('m_image', models.ImageField(upload_to='media/')),
                ('b_image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='b_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='f_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='m_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
