# Generated by Django 3.2 on 2021-05-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0019_auto_20210504_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='b_image',
            field=models.ImageField(upload_to='uploads/sell'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='f_image',
            field=models.ImageField(upload_to='uploads/sell'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='m_image',
            field=models.ImageField(upload_to='uploads/sell'),
        ),
    ]
