# Generated by Django 3.2 on 2021-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0022_auto_20210504_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='backimage',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='frontimage',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='indeximage',
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='back_image',
            field=models.ImageField(default='', upload_to='uploads/sell'),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='front_image',
            field=models.ImageField(default='', upload_to='uploads/sell'),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='index_image',
            field=models.ImageField(default='', upload_to='uploads/sell'),
        ),
    ]
