# Generated by Django 3.2 on 2021-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0023_auto_20210504_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_b',
            field=models.ImageField(default='', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_i',
            field=models.ImageField(default='', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
