# Generated by Django 3.2 on 2021-05-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0024_auto_20210504_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Chetan Bhagat', max_length=50),
        ),
    ]
