# Generated by Django 3.2 on 2021-05-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0027_feedback_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
