# Generated by Django 3.2 on 2021-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0028_feedback_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(default='Rupa Publications', max_length=500),
        ),
    ]
