# Generated by Django 3.2 on 2021-05-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0031_auto_20210529_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
