# Generated by Django 3.2 on 2021-05-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0032_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Dharwad', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(default='Hanuman Temple', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Cash On Delivery', max_length=50),
        ),
    ]
