# Generated by Django 3.2 on 2021-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0034_rename_payment_order_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.IntegerField(default=580001, max_length=6),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='address',
            field=models.CharField(default='Dharwad', max_length=100),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='city',
            field=models.CharField(default='Dharwad', max_length=20),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='isbn',
            field=models.IntegerField(default=123456789123, max_length=12),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='pin',
            field=models.CharField(default=580001, max_length=6),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='state',
            field=models.CharField(default='Karnataka', max_length=20),
        ),
    ]
