# Generated by Django 3.2 on 2021-05-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0035_auto_20210530_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.IntegerField(default=580001),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='isbn',
            field=models.IntegerField(default=123456789123),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='pin',
            field=models.IntegerField(default=580001),
        ),
    ]
