# Generated by Django 3.2 on 2021-06-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0036_auto_20210530_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='Kittle College road line bazar opposite national lodge', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Dharwad', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(default='Hanuman Temple', max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.IntegerField(default=580001),
        ),
    ]
