# Generated by Django 3.2 on 2021-06-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0038_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
