# Generated by Django 3.2 on 2021-06-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0040_rename_total_order_totals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totals',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=500),
        ),
    ]
