# Generated by Django 3.2 on 2021-06-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0041_auto_20210602_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
