# Generated by Django 3.2 on 2021-06-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0042_remove_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='Kittle College road line bazar opposite national lodge', max_length=100),
        ),
    ]
