# Generated by Django 3.2 on 2021-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0043_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
