# Generated by Django 3.2 on 2021-06-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0046_customer_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='quality',
            field=models.IntegerField(default=5),
        ),
    ]
