# Generated by Django 3.2 on 2021-06-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0047_feedback_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='exp',
            field=models.IntegerField(default=8),
        ),
    ]
