# Generated by Django 3.2 on 2021-04-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ISBN', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
